### ISSUE TITLE
Какая версия QT была использована?

### ISSUE THREAD

**Issue by Admor1702** [Piloswine1/comp_graphics_cpp#5]
На последней версии не видит либу QMatrix

**Comment by Piloswine1** [comment]
привет, на 5.15 собирается
![image](https://github.com/Piloswine1/comp_graphics_cpp/assets/55961738/bfa8a4d6-0c6f-46c9-94a0-9f82a25b11ea)

я там чутка поправил

**Comment by Admor1702** [comment]
Спасибо, брат! 407 группа не забудет тебя)

**Comment by Admor1702** [comment]
Мог бы оставить свой контакт? Или написать мне в ТГ (в профиле)

**Comment by Piloswine1** [comment]
Мог бы, но если вопросы по маевке, то бакалавриат я года 3 назад закончил, вряд ли чо-то вспомню
